=== folio-org/mod-erm-usage/ramls/schemas/aggregatorsetting.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "title": "Aggregator Settings Schema",
  "type": "object",
  "properties": {
    "id": {
      "type": "string"
    },
    "label": {
      "type": "string"
    },
    "username": {
      "type": "string",
      "description": "Username for web frontend of aggregator."
    },
    "password": {
      "type": "string",
      "description": "Hide in frontend, display to entitled users via “show” button, password for web frontend."
    },
    "apiKey": {
      "type": "string"
    },
    "serviceType": {
      "type": "string",
      "description": "Specifies implementation specific for this aggregator."
    },
    "serviceUrl": {
      "type": "string",
      "description": "Aggregator’s service URL to use for harvesting."
    },
    "accountConfig": {
      "type": "object",
      "properties": {
        "configType": {
          "description": "Specifies how the vendor's access parameters are submitted to the aggregator. These parameters are used by the aggregator to login into the vendor in order to fetch the usage data.",
          "type": "string",
          "enum": [
            "Mail",
            "API",
            "Manual"
          ]
        },
        "configMail": {
          "description": "Given if configType == mail",
          "type": "string"
        },
        "displayContact": {
          "description": "Free text info to display to the user with the SUSHI settings in the eUsage app frontend.",
          "type": "array",
          "minItems": 0,
          "items": {
            "type": "string"
          }
        }
      },
      "required": [
        "configType",
        "configMail"
      ]
    },
    "metadata": {
      "description": "Metadata about creation and changes, provided by the server (client should not provide)",
      "type": "object",
      "$ref": "../raml-util/schemas/metadata.schema",
      "readonly": true
    }
  },
  "required": [
    "id",
    "label",
    "username",
    "password",
    "serviceUrl",
    "accountConfig"
  ],
  "additionalProperties": false
}

=== folio-org/mod-erm-usage/mod-erm-usage-harvester/src/test/resources/__files/aggregator-setting.json
{
  "id": "54e8d70e-6ffe-4f1b-a3b0-534e95287680",
  "label": "Nationaler Statistikserver",
  "username": "user name",
  "password": "XXXuserpasswordXXX",
  "apiKey": "XXX123ABCXXX",
  "serviceType": "NSS",
  "serviceUrl": "https://stats.redi-bw.de/prod/Sushiservice/GetReport",
  "accountConfig": {
    "configType": "Manual",
    "configMail": "ab@counter-stats.com",
    "displayContact": [
      "Counter Aggregator Contact",
      "Tel: +49 1234 - 9876"
    ]
  }
}
